FROM python:3.7

ENV PYTHONUNBUFFERED 1

ADD . /wwwroot/
WORKDIR /wwwroot

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput

CMD gunicorn was.wsgi:application --bind 0.0.0.0:8000