FROM python:3.7

ENV PYTHONUNBUFFERED 1
ENV NEW_RELIC_CONFIG_FILE=newrelic.ini

ADD . /wwwroot/
WORKDIR /wwwroot

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install newrelic

CMD newrelic-admin run-program gunicorn was.wsgi:application --bind 0.0.0.0:8000